<?php
/**
 * Generated ISO 3166-1 country records. Do not edit directly.
 * Run: powershell -File tools/generate-iso-3166-1.ps1
 *
 * @package AxismundiGeodata
 */

defined( 'ABSPATH' ) || exit;

return array(
	'AD' => array( 'alpha_3' => 'AND', 'numeric' => '020', 'name' => 'Andorra' ),
	'AE' => array( 'alpha_3' => 'ARE', 'numeric' => '784', 'name' => 'United Arab Emirates' ),
	'AF' => array( 'alpha_3' => 'AFG', 'numeric' => '004', 'name' => 'Afghanistan' ),
	'AG' => array( 'alpha_3' => 'ATG', 'numeric' => '028', 'name' => 'Antigua and Barbuda' ),
	'AI' => array( 'alpha_3' => 'AIA', 'numeric' => '660', 'name' => 'Anguilla' ),
	'AL' => array( 'alpha_3' => 'ALB', 'numeric' => '008', 'name' => 'Albania' ),
	'AM' => array( 'alpha_3' => 'ARM', 'numeric' => '051', 'name' => 'Armenia' ),
	'AO' => array( 'alpha_3' => 'AGO', 'numeric' => '024', 'name' => 'Angola' ),
	'AQ' => array( 'alpha_3' => 'ATA', 'numeric' => '010', 'name' => 'Antarctica' ),
	'AR' => array( 'alpha_3' => 'ARG', 'numeric' => '032', 'name' => 'Argentina' ),
	'AS' => array( 'alpha_3' => 'ASM', 'numeric' => '016', 'name' => 'American Samoa' ),
	'AT' => array( 'alpha_3' => 'AUT', 'numeric' => '040', 'name' => 'Austria' ),
	'AU' => array( 'alpha_3' => 'AUS', 'numeric' => '036', 'name' => 'Australia' ),
	'AW' => array( 'alpha_3' => 'ABW', 'numeric' => '533', 'name' => 'Aruba' ),
	'AX' => array( 'alpha_3' => 'ALA', 'numeric' => '248', 'name' => 'Åland Islands' ),
	'AZ' => array( 'alpha_3' => 'AZE', 'numeric' => '031', 'name' => 'Azerbaijan' ),
	'BA' => array( 'alpha_3' => 'BIH', 'numeric' => '070', 'name' => 'Bosnia and Herzegovina' ),
	'BB' => array( 'alpha_3' => 'BRB', 'numeric' => '052', 'name' => 'Barbados' ),
	'BD' => array( 'alpha_3' => 'BGD', 'numeric' => '050', 'name' => 'Bangladesh' ),
	'BE' => array( 'alpha_3' => 'BEL', 'numeric' => '056', 'name' => 'Belgium' ),
	'BF' => array( 'alpha_3' => 'BFA', 'numeric' => '854', 'name' => 'Burkina Faso' ),
	'BG' => array( 'alpha_3' => 'BGR', 'numeric' => '100', 'name' => 'Bulgaria' ),
	'BH' => array( 'alpha_3' => 'BHR', 'numeric' => '048', 'name' => 'Bahrain' ),
	'BI' => array( 'alpha_3' => 'BDI', 'numeric' => '108', 'name' => 'Burundi' ),
	'BJ' => array( 'alpha_3' => 'BEN', 'numeric' => '204', 'name' => 'Benin' ),
	'BL' => array( 'alpha_3' => 'BLM', 'numeric' => '652', 'name' => 'Saint Barthélemy' ),
	'BM' => array( 'alpha_3' => 'BMU', 'numeric' => '060', 'name' => 'Bermuda' ),
	'BN' => array( 'alpha_3' => 'BRN', 'numeric' => '096', 'name' => 'Brunei Darussalam' ),
	'BO' => array( 'alpha_3' => 'BOL', 'numeric' => '068', 'name' => 'Bolivia' ),
	'BQ' => array( 'alpha_3' => 'BES', 'numeric' => '535', 'name' => 'Bonaire, Sint Eustatius and Saba' ),
	'BR' => array( 'alpha_3' => 'BRA', 'numeric' => '076', 'name' => 'Brazil' ),
	'BS' => array( 'alpha_3' => 'BHS', 'numeric' => '044', 'name' => 'Bahamas' ),
	'BT' => array( 'alpha_3' => 'BTN', 'numeric' => '064', 'name' => 'Bhutan' ),
	'BV' => array( 'alpha_3' => 'BVT', 'numeric' => '074', 'name' => 'Bouvet Island' ),
	'BW' => array( 'alpha_3' => 'BWA', 'numeric' => '072', 'name' => 'Botswana' ),
	'BY' => array( 'alpha_3' => 'BLR', 'numeric' => '112', 'name' => 'Belarus' ),
	'BZ' => array( 'alpha_3' => 'BLZ', 'numeric' => '084', 'name' => 'Belize' ),
	'CA' => array( 'alpha_3' => 'CAN', 'numeric' => '124', 'name' => 'Canada' ),
	'CC' => array( 'alpha_3' => 'CCK', 'numeric' => '166', 'name' => 'Cocos (Keeling) Islands' ),
	'CD' => array( 'alpha_3' => 'COD', 'numeric' => '180', 'name' => 'Congo, Democratic Republic of the' ),
	'CF' => array( 'alpha_3' => 'CAF', 'numeric' => '140', 'name' => 'Central African Republic' ),
	'CG' => array( 'alpha_3' => 'COG', 'numeric' => '178', 'name' => 'Congo' ),
	'CH' => array( 'alpha_3' => 'CHE', 'numeric' => '756', 'name' => 'Switzerland' ),
	'CI' => array( 'alpha_3' => 'CIV', 'numeric' => '384', 'name' => 'Côte d\'Ivoire' ),
	'CK' => array( 'alpha_3' => 'COK', 'numeric' => '184', 'name' => 'Cook Islands' ),
	'CL' => array( 'alpha_3' => 'CHL', 'numeric' => '152', 'name' => 'Chile' ),
	'CM' => array( 'alpha_3' => 'CMR', 'numeric' => '120', 'name' => 'Cameroon' ),
	'CN' => array( 'alpha_3' => 'CHN', 'numeric' => '156', 'name' => 'China' ),
	'CO' => array( 'alpha_3' => 'COL', 'numeric' => '170', 'name' => 'Colombia' ),
	'CR' => array( 'alpha_3' => 'CRI', 'numeric' => '188', 'name' => 'Costa Rica' ),
	'CU' => array( 'alpha_3' => 'CUB', 'numeric' => '192', 'name' => 'Cuba' ),
	'CV' => array( 'alpha_3' => 'CPV', 'numeric' => '132', 'name' => 'Cabo Verde' ),
	'CW' => array( 'alpha_3' => 'CUW', 'numeric' => '531', 'name' => 'Curaçao' ),
	'CX' => array( 'alpha_3' => 'CXR', 'numeric' => '162', 'name' => 'Christmas Island' ),
	'CY' => array( 'alpha_3' => 'CYP', 'numeric' => '196', 'name' => 'Cyprus' ),
	'CZ' => array( 'alpha_3' => 'CZE', 'numeric' => '203', 'name' => 'Czechia' ),
	'DE' => array( 'alpha_3' => 'DEU', 'numeric' => '276', 'name' => 'Germany' ),
	'DJ' => array( 'alpha_3' => 'DJI', 'numeric' => '262', 'name' => 'Djibouti' ),
	'DK' => array( 'alpha_3' => 'DNK', 'numeric' => '208', 'name' => 'Denmark' ),
	'DM' => array( 'alpha_3' => 'DMA', 'numeric' => '212', 'name' => 'Dominica' ),
	'DO' => array( 'alpha_3' => 'DOM', 'numeric' => '214', 'name' => 'Dominican Republic' ),
	'DZ' => array( 'alpha_3' => 'DZA', 'numeric' => '012', 'name' => 'Algeria' ),
	'EC' => array( 'alpha_3' => 'ECU', 'numeric' => '218', 'name' => 'Ecuador' ),
	'EE' => array( 'alpha_3' => 'EST', 'numeric' => '233', 'name' => 'Estonia' ),
	'EG' => array( 'alpha_3' => 'EGY', 'numeric' => '818', 'name' => 'Egypt' ),
	'EH' => array( 'alpha_3' => 'ESH', 'numeric' => '732', 'name' => 'Western Sahara' ),
	'ER' => array( 'alpha_3' => 'ERI', 'numeric' => '232', 'name' => 'Eritrea' ),
	'ES' => array( 'alpha_3' => 'ESP', 'numeric' => '724', 'name' => 'Spain' ),
	'ET' => array( 'alpha_3' => 'ETH', 'numeric' => '231', 'name' => 'Ethiopia' ),
	'FI' => array( 'alpha_3' => 'FIN', 'numeric' => '246', 'name' => 'Finland' ),
	'FJ' => array( 'alpha_3' => 'FJI', 'numeric' => '242', 'name' => 'Fiji' ),
	'FK' => array( 'alpha_3' => 'FLK', 'numeric' => '238', 'name' => 'Falkland Islands' ),
	'FM' => array( 'alpha_3' => 'FSM', 'numeric' => '583', 'name' => 'Micronesia' ),
	'FO' => array( 'alpha_3' => 'FRO', 'numeric' => '234', 'name' => 'Faroe Islands' ),
	'FR' => array( 'alpha_3' => 'FRA', 'numeric' => '250', 'name' => 'France' ),
	'GA' => array( 'alpha_3' => 'GAB', 'numeric' => '266', 'name' => 'Gabon' ),
	'GB' => array( 'alpha_3' => 'GBR', 'numeric' => '826', 'name' => 'United Kingdom' ),
	'GD' => array( 'alpha_3' => 'GRD', 'numeric' => '308', 'name' => 'Grenada' ),
	'GE' => array( 'alpha_3' => 'GEO', 'numeric' => '268', 'name' => 'Georgia' ),
	'GF' => array( 'alpha_3' => 'GUF', 'numeric' => '254', 'name' => 'French Guiana' ),
	'GG' => array( 'alpha_3' => 'GGY', 'numeric' => '831', 'name' => 'Guernsey' ),
	'GH' => array( 'alpha_3' => 'GHA', 'numeric' => '288', 'name' => 'Ghana' ),
	'GI' => array( 'alpha_3' => 'GIB', 'numeric' => '292', 'name' => 'Gibraltar' ),
	'GL' => array( 'alpha_3' => 'GRL', 'numeric' => '304', 'name' => 'Greenland' ),
	'GM' => array( 'alpha_3' => 'GMB', 'numeric' => '270', 'name' => 'Gambia' ),
	'GN' => array( 'alpha_3' => 'GIN', 'numeric' => '324', 'name' => 'Guinea' ),
	'GP' => array( 'alpha_3' => 'GLP', 'numeric' => '312', 'name' => 'Guadeloupe' ),
	'GQ' => array( 'alpha_3' => 'GNQ', 'numeric' => '226', 'name' => 'Equatorial Guinea' ),
	'GR' => array( 'alpha_3' => 'GRC', 'numeric' => '300', 'name' => 'Greece' ),
	'GS' => array( 'alpha_3' => 'SGS', 'numeric' => '239', 'name' => 'South Georgia and the South Sandwich Islands' ),
	'GT' => array( 'alpha_3' => 'GTM', 'numeric' => '320', 'name' => 'Guatemala' ),
	'GU' => array( 'alpha_3' => 'GUM', 'numeric' => '316', 'name' => 'Guam' ),
	'GW' => array( 'alpha_3' => 'GNB', 'numeric' => '624', 'name' => 'Guinea-Bissau' ),
	'GY' => array( 'alpha_3' => 'GUY', 'numeric' => '328', 'name' => 'Guyana' ),
	'HK' => array( 'alpha_3' => 'HKG', 'numeric' => '344', 'name' => 'Hong Kong' ),
	'HM' => array( 'alpha_3' => 'HMD', 'numeric' => '334', 'name' => 'Heard Island and McDonald Islands' ),
	'HN' => array( 'alpha_3' => 'HND', 'numeric' => '340', 'name' => 'Honduras' ),
	'HR' => array( 'alpha_3' => 'HRV', 'numeric' => '191', 'name' => 'Croatia' ),
	'HT' => array( 'alpha_3' => 'HTI', 'numeric' => '332', 'name' => 'Haiti' ),
	'HU' => array( 'alpha_3' => 'HUN', 'numeric' => '348', 'name' => 'Hungary' ),
	'ID' => array( 'alpha_3' => 'IDN', 'numeric' => '360', 'name' => 'Indonesia' ),
	'IE' => array( 'alpha_3' => 'IRL', 'numeric' => '372', 'name' => 'Ireland' ),
	'IL' => array( 'alpha_3' => 'ISR', 'numeric' => '376', 'name' => 'Israel' ),
	'IM' => array( 'alpha_3' => 'IMN', 'numeric' => '833', 'name' => 'Isle of Man' ),
	'IN' => array( 'alpha_3' => 'IND', 'numeric' => '356', 'name' => 'India' ),
	'IO' => array( 'alpha_3' => 'IOT', 'numeric' => '086', 'name' => 'British Indian Ocean Territory' ),
	'IQ' => array( 'alpha_3' => 'IRQ', 'numeric' => '368', 'name' => 'Iraq' ),
	'IR' => array( 'alpha_3' => 'IRN', 'numeric' => '364', 'name' => 'Iran' ),
	'IS' => array( 'alpha_3' => 'ISL', 'numeric' => '352', 'name' => 'Iceland' ),
	'IT' => array( 'alpha_3' => 'ITA', 'numeric' => '380', 'name' => 'Italy' ),
	'JE' => array( 'alpha_3' => 'JEY', 'numeric' => '832', 'name' => 'Jersey' ),
	'JM' => array( 'alpha_3' => 'JAM', 'numeric' => '388', 'name' => 'Jamaica' ),
	'JO' => array( 'alpha_3' => 'JOR', 'numeric' => '400', 'name' => 'Jordan' ),
	'JP' => array( 'alpha_3' => 'JPN', 'numeric' => '392', 'name' => 'Japan' ),
	'KE' => array( 'alpha_3' => 'KEN', 'numeric' => '404', 'name' => 'Kenya' ),
	'KG' => array( 'alpha_3' => 'KGZ', 'numeric' => '417', 'name' => 'Kyrgyzstan' ),
	'KH' => array( 'alpha_3' => 'KHM', 'numeric' => '116', 'name' => 'Cambodia' ),
	'KI' => array( 'alpha_3' => 'KIR', 'numeric' => '296', 'name' => 'Kiribati' ),
	'KM' => array( 'alpha_3' => 'COM', 'numeric' => '174', 'name' => 'Comoros' ),
	'KN' => array( 'alpha_3' => 'KNA', 'numeric' => '659', 'name' => 'Saint Kitts and Nevis' ),
	'KP' => array( 'alpha_3' => 'PRK', 'numeric' => '408', 'name' => 'Korea, Democratic People\'s Republic of' ),
	'KR' => array( 'alpha_3' => 'KOR', 'numeric' => '410', 'name' => 'Korea, Republic of' ),
	'KW' => array( 'alpha_3' => 'KWT', 'numeric' => '414', 'name' => 'Kuwait' ),
	'KY' => array( 'alpha_3' => 'CYM', 'numeric' => '136', 'name' => 'Cayman Islands' ),
	'KZ' => array( 'alpha_3' => 'KAZ', 'numeric' => '398', 'name' => 'Kazakhstan' ),
	'LA' => array( 'alpha_3' => 'LAO', 'numeric' => '418', 'name' => 'Lao People\'s Democratic Republic' ),
	'LB' => array( 'alpha_3' => 'LBN', 'numeric' => '422', 'name' => 'Lebanon' ),
	'LC' => array( 'alpha_3' => 'LCA', 'numeric' => '662', 'name' => 'Saint Lucia' ),
	'LI' => array( 'alpha_3' => 'LIE', 'numeric' => '438', 'name' => 'Liechtenstein' ),
	'LK' => array( 'alpha_3' => 'LKA', 'numeric' => '144', 'name' => 'Sri Lanka' ),
	'LR' => array( 'alpha_3' => 'LBR', 'numeric' => '430', 'name' => 'Liberia' ),
	'LS' => array( 'alpha_3' => 'LSO', 'numeric' => '426', 'name' => 'Lesotho' ),
	'LT' => array( 'alpha_3' => 'LTU', 'numeric' => '440', 'name' => 'Lithuania' ),
	'LU' => array( 'alpha_3' => 'LUX', 'numeric' => '442', 'name' => 'Luxembourg' ),
	'LV' => array( 'alpha_3' => 'LVA', 'numeric' => '428', 'name' => 'Latvia' ),
	'LY' => array( 'alpha_3' => 'LBY', 'numeric' => '434', 'name' => 'Libya' ),
	'MA' => array( 'alpha_3' => 'MAR', 'numeric' => '504', 'name' => 'Morocco' ),
	'MC' => array( 'alpha_3' => 'MCO', 'numeric' => '492', 'name' => 'Monaco' ),
	'MD' => array( 'alpha_3' => 'MDA', 'numeric' => '498', 'name' => 'Moldova' ),
	'ME' => array( 'alpha_3' => 'MNE', 'numeric' => '499', 'name' => 'Montenegro' ),
	'MF' => array( 'alpha_3' => 'MAF', 'numeric' => '663', 'name' => 'Saint Martin (French part)' ),
	'MG' => array( 'alpha_3' => 'MDG', 'numeric' => '450', 'name' => 'Madagascar' ),
	'MH' => array( 'alpha_3' => 'MHL', 'numeric' => '584', 'name' => 'Marshall Islands' ),
	'MK' => array( 'alpha_3' => 'MKD', 'numeric' => '807', 'name' => 'North Macedonia' ),
	'ML' => array( 'alpha_3' => 'MLI', 'numeric' => '466', 'name' => 'Mali' ),
	'MM' => array( 'alpha_3' => 'MMR', 'numeric' => '104', 'name' => 'Myanmar' ),
	'MN' => array( 'alpha_3' => 'MNG', 'numeric' => '496', 'name' => 'Mongolia' ),
	'MO' => array( 'alpha_3' => 'MAC', 'numeric' => '446', 'name' => 'Macao' ),
	'MP' => array( 'alpha_3' => 'MNP', 'numeric' => '580', 'name' => 'Northern Mariana Islands' ),
	'MQ' => array( 'alpha_3' => 'MTQ', 'numeric' => '474', 'name' => 'Martinique' ),
	'MR' => array( 'alpha_3' => 'MRT', 'numeric' => '478', 'name' => 'Mauritania' ),
	'MS' => array( 'alpha_3' => 'MSR', 'numeric' => '500', 'name' => 'Montserrat' ),
	'MT' => array( 'alpha_3' => 'MLT', 'numeric' => '470', 'name' => 'Malta' ),
	'MU' => array( 'alpha_3' => 'MUS', 'numeric' => '480', 'name' => 'Mauritius' ),
	'MV' => array( 'alpha_3' => 'MDV', 'numeric' => '462', 'name' => 'Maldives' ),
	'MW' => array( 'alpha_3' => 'MWI', 'numeric' => '454', 'name' => 'Malawi' ),
	'MX' => array( 'alpha_3' => 'MEX', 'numeric' => '484', 'name' => 'Mexico' ),
	'MY' => array( 'alpha_3' => 'MYS', 'numeric' => '458', 'name' => 'Malaysia' ),
	'MZ' => array( 'alpha_3' => 'MOZ', 'numeric' => '508', 'name' => 'Mozambique' ),
	'NA' => array( 'alpha_3' => 'NAM', 'numeric' => '516', 'name' => 'Namibia' ),
	'NC' => array( 'alpha_3' => 'NCL', 'numeric' => '540', 'name' => 'New Caledonia' ),
	'NE' => array( 'alpha_3' => 'NER', 'numeric' => '562', 'name' => 'Niger' ),
	'NF' => array( 'alpha_3' => 'NFK', 'numeric' => '574', 'name' => 'Norfolk Island' ),
	'NG' => array( 'alpha_3' => 'NGA', 'numeric' => '566', 'name' => 'Nigeria' ),
	'NI' => array( 'alpha_3' => 'NIC', 'numeric' => '558', 'name' => 'Nicaragua' ),
	'NL' => array( 'alpha_3' => 'NLD', 'numeric' => '528', 'name' => 'Netherlands' ),
	'NO' => array( 'alpha_3' => 'NOR', 'numeric' => '578', 'name' => 'Norway' ),
	'NP' => array( 'alpha_3' => 'NPL', 'numeric' => '524', 'name' => 'Nepal' ),
	'NR' => array( 'alpha_3' => 'NRU', 'numeric' => '520', 'name' => 'Nauru' ),
	'NU' => array( 'alpha_3' => 'NIU', 'numeric' => '570', 'name' => 'Niue' ),
	'NZ' => array( 'alpha_3' => 'NZL', 'numeric' => '554', 'name' => 'New Zealand' ),
	'OM' => array( 'alpha_3' => 'OMN', 'numeric' => '512', 'name' => 'Oman' ),
	'PA' => array( 'alpha_3' => 'PAN', 'numeric' => '591', 'name' => 'Panama' ),
	'PE' => array( 'alpha_3' => 'PER', 'numeric' => '604', 'name' => 'Peru' ),
	'PF' => array( 'alpha_3' => 'PYF', 'numeric' => '258', 'name' => 'French Polynesia' ),
	'PG' => array( 'alpha_3' => 'PNG', 'numeric' => '598', 'name' => 'Papua New Guinea' ),
	'PH' => array( 'alpha_3' => 'PHL', 'numeric' => '608', 'name' => 'Philippines' ),
	'PK' => array( 'alpha_3' => 'PAK', 'numeric' => '586', 'name' => 'Pakistan' ),
	'PL' => array( 'alpha_3' => 'POL', 'numeric' => '616', 'name' => 'Poland' ),
	'PM' => array( 'alpha_3' => 'SPM', 'numeric' => '666', 'name' => 'Saint Pierre and Miquelon' ),
	'PN' => array( 'alpha_3' => 'PCN', 'numeric' => '612', 'name' => 'Pitcairn' ),
	'PR' => array( 'alpha_3' => 'PRI', 'numeric' => '630', 'name' => 'Puerto Rico' ),
	'PS' => array( 'alpha_3' => 'PSE', 'numeric' => '275', 'name' => 'Palestine, State of' ),
	'PT' => array( 'alpha_3' => 'PRT', 'numeric' => '620', 'name' => 'Portugal' ),
	'PW' => array( 'alpha_3' => 'PLW', 'numeric' => '585', 'name' => 'Palau' ),
	'PY' => array( 'alpha_3' => 'PRY', 'numeric' => '600', 'name' => 'Paraguay' ),
	'QA' => array( 'alpha_3' => 'QAT', 'numeric' => '634', 'name' => 'Qatar' ),
	'RE' => array( 'alpha_3' => 'REU', 'numeric' => '638', 'name' => 'Réunion' ),
	'RO' => array( 'alpha_3' => 'ROU', 'numeric' => '642', 'name' => 'Romania' ),
	'RS' => array( 'alpha_3' => 'SRB', 'numeric' => '688', 'name' => 'Serbia' ),
	'RU' => array( 'alpha_3' => 'RUS', 'numeric' => '643', 'name' => 'Russian Federation' ),
	'RW' => array( 'alpha_3' => 'RWA', 'numeric' => '646', 'name' => 'Rwanda' ),
	'SA' => array( 'alpha_3' => 'SAU', 'numeric' => '682', 'name' => 'Saudi Arabia' ),
	'SB' => array( 'alpha_3' => 'SLB', 'numeric' => '090', 'name' => 'Solomon Islands' ),
	'SC' => array( 'alpha_3' => 'SYC', 'numeric' => '690', 'name' => 'Seychelles' ),
	'SD' => array( 'alpha_3' => 'SDN', 'numeric' => '729', 'name' => 'Sudan' ),
	'SE' => array( 'alpha_3' => 'SWE', 'numeric' => '752', 'name' => 'Sweden' ),
	'SG' => array( 'alpha_3' => 'SGP', 'numeric' => '702', 'name' => 'Singapore' ),
	'SH' => array( 'alpha_3' => 'SHN', 'numeric' => '654', 'name' => 'Saint Helena, Ascension and Tristan da Cunha' ),
	'SI' => array( 'alpha_3' => 'SVN', 'numeric' => '705', 'name' => 'Slovenia' ),
	'SJ' => array( 'alpha_3' => 'SJM', 'numeric' => '744', 'name' => 'Svalbard and Jan Mayen' ),
	'SK' => array( 'alpha_3' => 'SVK', 'numeric' => '703', 'name' => 'Slovakia' ),
	'SL' => array( 'alpha_3' => 'SLE', 'numeric' => '694', 'name' => 'Sierra Leone' ),
	'SM' => array( 'alpha_3' => 'SMR', 'numeric' => '674', 'name' => 'San Marino' ),
	'SN' => array( 'alpha_3' => 'SEN', 'numeric' => '686', 'name' => 'Senegal' ),
	'SO' => array( 'alpha_3' => 'SOM', 'numeric' => '706', 'name' => 'Somalia' ),
	'SR' => array( 'alpha_3' => 'SUR', 'numeric' => '740', 'name' => 'Suriname' ),
	'SS' => array( 'alpha_3' => 'SSD', 'numeric' => '728', 'name' => 'South Sudan' ),
	'ST' => array( 'alpha_3' => 'STP', 'numeric' => '678', 'name' => 'Sao Tome and Principe' ),
	'SV' => array( 'alpha_3' => 'SLV', 'numeric' => '222', 'name' => 'El Salvador' ),
	'SX' => array( 'alpha_3' => 'SXM', 'numeric' => '534', 'name' => 'Sint Maarten (Dutch part)' ),
	'SY' => array( 'alpha_3' => 'SYR', 'numeric' => '760', 'name' => 'Syrian Arab Republic' ),
	'SZ' => array( 'alpha_3' => 'SWZ', 'numeric' => '748', 'name' => 'Eswatini' ),
	'TC' => array( 'alpha_3' => 'TCA', 'numeric' => '796', 'name' => 'Turks and Caicos Islands' ),
	'TD' => array( 'alpha_3' => 'TCD', 'numeric' => '148', 'name' => 'Chad' ),
	'TF' => array( 'alpha_3' => 'ATF', 'numeric' => '260', 'name' => 'French Southern Territories' ),
	'TG' => array( 'alpha_3' => 'TGO', 'numeric' => '768', 'name' => 'Togo' ),
	'TH' => array( 'alpha_3' => 'THA', 'numeric' => '764', 'name' => 'Thailand' ),
	'TJ' => array( 'alpha_3' => 'TJK', 'numeric' => '762', 'name' => 'Tajikistan' ),
	'TK' => array( 'alpha_3' => 'TKL', 'numeric' => '772', 'name' => 'Tokelau' ),
	'TL' => array( 'alpha_3' => 'TLS', 'numeric' => '626', 'name' => 'Timor-Leste' ),
	'TM' => array( 'alpha_3' => 'TKM', 'numeric' => '795', 'name' => 'Turkmenistan' ),
	'TN' => array( 'alpha_3' => 'TUN', 'numeric' => '788', 'name' => 'Tunisia' ),
	'TO' => array( 'alpha_3' => 'TON', 'numeric' => '776', 'name' => 'Tonga' ),
	'TR' => array( 'alpha_3' => 'TUR', 'numeric' => '792', 'name' => 'Türkiye' ),
	'TT' => array( 'alpha_3' => 'TTO', 'numeric' => '780', 'name' => 'Trinidad and Tobago' ),
	'TV' => array( 'alpha_3' => 'TUV', 'numeric' => '798', 'name' => 'Tuvalu' ),
	'TW' => array( 'alpha_3' => 'TWN', 'numeric' => '158', 'name' => 'Taiwan' ),
	'TZ' => array( 'alpha_3' => 'TZA', 'numeric' => '834', 'name' => 'Tanzania' ),
	'UA' => array( 'alpha_3' => 'UKR', 'numeric' => '804', 'name' => 'Ukraine' ),
	'UG' => array( 'alpha_3' => 'UGA', 'numeric' => '800', 'name' => 'Uganda' ),
	'UM' => array( 'alpha_3' => 'UMI', 'numeric' => '581', 'name' => 'United States Minor Outlying Islands' ),
	'US' => array( 'alpha_3' => 'USA', 'numeric' => '840', 'name' => 'United States of America' ),
	'UY' => array( 'alpha_3' => 'URY', 'numeric' => '858', 'name' => 'Uruguay' ),
	'UZ' => array( 'alpha_3' => 'UZB', 'numeric' => '860', 'name' => 'Uzbekistan' ),
	'VA' => array( 'alpha_3' => 'VAT', 'numeric' => '336', 'name' => 'Holy See' ),
	'VC' => array( 'alpha_3' => 'VCT', 'numeric' => '670', 'name' => 'Saint Vincent and the Grenadines' ),
	'VE' => array( 'alpha_3' => 'VEN', 'numeric' => '862', 'name' => 'Venezuela' ),
	'VG' => array( 'alpha_3' => 'VGB', 'numeric' => '092', 'name' => 'Virgin Islands (British)' ),
	'VI' => array( 'alpha_3' => 'VIR', 'numeric' => '850', 'name' => 'Virgin Islands (U.S.)' ),
	'VN' => array( 'alpha_3' => 'VNM', 'numeric' => '704', 'name' => 'Viet Nam' ),
	'VU' => array( 'alpha_3' => 'VUT', 'numeric' => '548', 'name' => 'Vanuatu' ),
	'WF' => array( 'alpha_3' => 'WLF', 'numeric' => '876', 'name' => 'Wallis and Futuna' ),
	'WS' => array( 'alpha_3' => 'WSM', 'numeric' => '882', 'name' => 'Samoa' ),
	'YE' => array( 'alpha_3' => 'YEM', 'numeric' => '887', 'name' => 'Yemen' ),
	'YT' => array( 'alpha_3' => 'MYT', 'numeric' => '175', 'name' => 'Mayotte' ),
	'ZA' => array( 'alpha_3' => 'ZAF', 'numeric' => '710', 'name' => 'South Africa' ),
	'ZM' => array( 'alpha_3' => 'ZMB', 'numeric' => '894', 'name' => 'Zambia' ),
	'ZW' => array( 'alpha_3' => 'ZWE', 'numeric' => '716', 'name' => 'Zimbabwe' ),
);
