<?php
/**
 * Unicode RGI emoji catalogue: the data every Unicode picker reads.
 *
 * Picker metadata, not a registry. A Unicode grapheme needs no row, no review and no
 * declaration to be valid; anything that accepts one (Activities' reaction normalizer, the
 * renderer) must keep working without consulting this data, so a newer peer's emoji is
 * never refused because this site has not rebuilt its catalogue yet.
 *
 * Moved here from Axismundi Activities, which built it for the reaction picker. The data
 * is about emoji, not about reactions, and Emoji ships without Activities, so Emoji owns
 * it and Activities reads it through axismundi_emoji_unicode_picker_source().
 *
 * Generated by scripts/build-unicode-emoji-catalogue.py from the same emoji-test.txt the
 * flags font subset is built from.
 *
 * @package AxismundiEmoji
 */

defined( 'ABSPATH' ) || exit;

const AXISMUNDI_EMOJI_UNICODE_CATALOGUE_SCHEMA  = 1;
const AXISMUNDI_EMOJI_UNICODE_CATALOGUE_VERSION = '17.0';
const AXISMUNDI_EMOJI_UNICODE_CATALOGUE_DIR     = 'assets/unicode/catalogue';

/** Absolute path to the full generated index. */
function axismundi_emoji_unicode_catalogue_path() : string {
	return dirname( __DIR__ ) . '/' . AXISMUNDI_EMOJI_UNICODE_CATALOGUE_DIR . '/rgi-' . AXISMUNDI_EMOJI_UNICODE_CATALOGUE_VERSION . '.json';
}

/**
 * Load and validate the generated index once per request.
 *
 * A broken or missing file means pickers have no Unicode choices, nothing more.
 *
 * @return array{schema:int,unicodeVersion:string,source:string,sourceSha256:string,items:array<int,array<string,mixed>>}
 */
function axismundi_emoji_unicode_catalogue() : array {
	static $catalogue = null;
	if ( is_array( $catalogue ) ) {
		return $catalogue;
	}

	$catalogue = array(
		'schema'         => AXISMUNDI_EMOJI_UNICODE_CATALOGUE_SCHEMA,
		'unicodeVersion' => AXISMUNDI_EMOJI_UNICODE_CATALOGUE_VERSION,
		'source'         => '',
		'sourceSha256'   => '',
		'items'          => array(),
	);
	$path = axismundi_emoji_unicode_catalogue_path();
	$json = is_readable( $path ) ? file_get_contents( $path ) : false;
	$data = is_string( $json ) ? json_decode( $json, true ) : null;
	if (
		! is_array( $data )
		|| AXISMUNDI_EMOJI_UNICODE_CATALOGUE_SCHEMA !== (int) ( $data['schema'] ?? 0 )
		|| AXISMUNDI_EMOJI_UNICODE_CATALOGUE_VERSION !== (string) ( $data['unicodeVersion'] ?? '' )
		|| ! is_array( $data['items'] ?? null )
	) {
		return $catalogue;
	}

	foreach ( $data['items'] as $item ) {
		if (
			! is_array( $item )
			|| '' === (string) ( $item['emoji'] ?? '' )
			|| ! preg_match( '/^unicode:U\+[0-9A-F]+(?:-U\+[0-9A-F]+)*$/', (string) ( $item['key'] ?? '' ) )
		) {
			continue;
		}
		$catalogue['items'][] = array(
			'emoji'        => (string) $item['emoji'],
			'key'          => (string) $item['key'],
			'group'        => (string) ( $item['group'] ?? '' ),
			'subgroup'     => (string) ( $item['subgroup'] ?? '' ),
			'name'         => (string) ( $item['name'] ?? '' ),
			'keywords'     => array_values( array_filter( array_map( 'strval', (array) ( $item['keywords'] ?? array() ) ) ) ),
			'emojiVersion' => (string) ( $item['emojiVersion'] ?? '' ),
		);
	}
	$catalogue['source']       = (string) ( $data['source'] ?? '' );
	$catalogue['sourceSha256'] = (string) ( $data['sourceSha256'] ?? '' );
	return $catalogue;
}

/** Case-fold a query without requiring mbstring. */
function axismundi_emoji_unicode_catalogue_fold( string $value ) : string {
	return function_exists( 'mb_strtolower' ) ? mb_strtolower( $value, 'UTF-8' ) : strtolower( $value );
}

/**
 * Find entries by their standardized English metadata.
 *
 * There is intentionally no made-up localisation here. A translated search index can be
 * layered over this exact data later; claiming Korean search before providing Korean data
 * would make a picker look partially broken.
 *
 * @return array{items:array<int,array<string,mixed>>,total:int,total_pages:int,page:int,per_page:int}
 */
function axismundi_emoji_find_unicode( string $search = '', string $group = '', int $page = 1, int $per_page = 100 ) : array {
	$needle  = axismundi_emoji_unicode_catalogue_fold( trim( $search ) );
	$group   = trim( $group );
	$matches = array();
	foreach ( axismundi_emoji_unicode_catalogue()['items'] as $item ) {
		if ( '' !== $group && $group !== $item['group'] ) {
			continue;
		}
		if ( '' !== $needle ) {
			$haystack = implode( ' ', array_merge( array( $item['emoji'], $item['key'], $item['group'], $item['subgroup'], $item['name'] ), $item['keywords'] ) );
			if ( ! str_contains( axismundi_emoji_unicode_catalogue_fold( $haystack ), $needle ) ) {
				continue;
			}
		}
		$matches[] = $item;
	}

	$per_page    = max( 1, min( 100, $per_page ) );
	$total       = count( $matches );
	$total_pages = max( 1, (int) ceil( $total / $per_page ) );
	$page        = max( 1, min( $total_pages, $page ) );
	return array(
		'items'       => array_slice( $matches, ( $page - 1 ) * $per_page, $per_page ),
		'total'       => $total,
		'total_pages' => $total_pages,
		'page'        => $page,
		'per_page'    => $per_page,
	);
}

/** @return string[] Unicode Emoji group names in Unicode's display order. */
function axismundi_emoji_unicode_groups() : array {
	$groups = array();
	foreach ( axismundi_emoji_unicode_catalogue()['items'] as $item ) {
		if ( '' !== $item['group'] && ! in_array( $item['group'], $groups, true ) ) {
			$groups[] = $item['group'];
		}
	}
	return $groups;
}

/**
 * Where a picker gets the Unicode set, and how it is divided.
 *
 * Static files rather than the REST route: the route pages at 100 and a picker wants whole
 * groups, so it would take forty round trips to fill one panel. The files are public and
 * versioned by name, which makes them exactly what an HTTP cache is for. The REST route
 * stays for consumers that want to search or page.
 *
 * Groups come from the same index, so a picker cannot list a heading the data lacks.
 *
 * @return array{index_url:string,groups:array<string,string>} Group name => URL of its file.
 */
function axismundi_emoji_unicode_picker_source() : array {
	$base = dirname( __DIR__ ) . '/axismundi-emoji.php';
	$dir  = AXISMUNDI_EMOJI_UNICODE_CATALOGUE_DIR . '/rgi-' . AXISMUNDI_EMOJI_UNICODE_CATALOGUE_VERSION;
	$urls = array();
	foreach ( axismundi_emoji_unicode_groups() as $group ) {
		$slug = trim( (string) preg_replace( '/[^a-z0-9]+/', '-', strtolower( str_replace( '&', 'and', $group ) ) ), '-' );
		if ( is_readable( dirname( __DIR__ ) . '/' . $dir . '/' . $slug . '.json' ) ) {
			$urls[ $group ] = plugins_url( $dir . '/' . $slug . '.json', $base );
		}
	}
	$index = axismundi_emoji_unicode_catalogue_path();
	return array(
		'index_url' => is_readable( $index ) ? plugins_url( AXISMUNDI_EMOJI_UNICODE_CATALOGUE_DIR . '/' . basename( $index ), $base ) : '',
		'groups'    => $urls,
	);
}

/** Register the static, public Unicode catalogue route. */
function axismundi_emoji_register_unicode_catalogue_route() : void {
	register_rest_route(
		'axismundi/v1',
		'/emoji/unicode',
		array(
			'methods'             => WP_REST_Server::READABLE,
			'callback'            => 'axismundi_emoji_rest_unicode_catalogue',
			// Standard Unicode metadata only: no local emoji, usage history, or viewer state,
			// so it is deliberately public and cacheable.
			'permission_callback' => '__return_true',
			'args'                => array(
				'search'   => array( 'type' => 'string', 'default' => '' ),
				'group'    => array( 'type' => 'string', 'default' => '' ),
				'page'     => array( 'type' => 'integer', 'default' => 1, 'minimum' => 1 ),
				'per_page' => array( 'type' => 'integer', 'default' => 100, 'minimum' => 1, 'maximum' => 100 ),
			),
		)
	);
}
add_action( 'rest_api_init', 'axismundi_emoji_register_unicode_catalogue_route' );

/** Answer one page of the catalogue. */
function axismundi_emoji_rest_unicode_catalogue( WP_REST_Request $request ) : WP_REST_Response {
	$page      = axismundi_emoji_find_unicode( (string) $request['search'], (string) $request['group'], (int) $request['page'], (int) $request['per_page'] );
	$catalogue = axismundi_emoji_unicode_catalogue();
	$response  = new WP_REST_Response(
		array(
			'schema'          => $catalogue['schema'],
			'unicode_version' => $catalogue['unicodeVersion'],
			'groups'          => axismundi_emoji_unicode_groups(),
			'items'           => $page['items'],
		),
		200
	);
	$response->header( 'X-WP-Total', (string) $page['total'] );
	$response->header( 'X-WP-TotalPages', (string) $page['total_pages'] );
	$response->header( 'Cache-Control', 'public, max-age=86400' );
	return $response;
}
