<?php
/**
 * Axismundi Pilot — color-scheme.asset.php (pre-built)
 *
 * Dependency manifest for the color-scheme script module.
 * Normally generated by @wordpress/scripts webpack build.
 *
 * Run `npm install && npm run build` in the axismundi-pilot directory
 * to regenerate this file with a proper content-hash version string.
 */
return array(
	'dependencies' => array( '@wordpress/interactivity' ),
	'version'      => '1.0.0-prebuild',
);
